// <auto-generated />
namespace ScoutsHonour.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class LimitcodesinGroupmodelto20chars : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(LimitcodesinGroupmodelto20chars));
        
        string IMigrationMetadata.Id
        {
            get { return "201408031100037_Limit codes in Group model to 20 chars"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
